export const GET_NEW_ARRIV_PROD_REQUEST = 'GET_NEW_ARRIV_PROD_REQUEST';
export const GET_NEW_ARRIV_PROD_SUCCESS ='GET_NEW_ARRIV_PROD_SUCCESS';
export const GET_NEW_ARRIV_PROD_FAILURE = 'GET_NEW_ARRIV_PROD_FAILURE';